version: "3.3"

services:

  task-db-mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: task_db
    ports:
      - 3306:3306
    restart: on-failure